USE GUIA_TUR;

Create table IF NOT EXISTS pais (

 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 NOME VARCHAR(50) NOT NULL DEFAULT '',
 CONTINENTE ENUM ('ASIA' , 'AMERICA') DEFAULT 'AMERICA',
 CODIGO CHAR(3) NOT NULL
); 